version: '3'

services:
  mongodb:
    image: mongo
    container_name: bms_db
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodb_data_container:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: bms_user
        MONGO_INITDB_ROOT_PASSWORD: bms_password
        MONGO_INITDB_DATABASE: bms_db
    networks: 
      - mongodb_network

  mongoadmin:
    image: mongo-express
    container_name: bms_admin
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: bms_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: bms_password
    ports:
      - 8081:8081
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb_data_container:
  static: